### ISSUE TITLE
check_failure fails to fail

### ISSUE THREAD

**Issue by lovettchris** [leanprover/theorem_proving_in_lean4#15] opened 2021-11-12 18:32 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

From [type_classes Output Parameters](https://github.com/leanprover/theorem_proving_in_lean4/blob/master/type_classes.md#output-parameters)

By default, Lean only tries to synthesize an instance `Inhabited T` when the term `T` is known and does not
contain missing parts. The following command produces the error
"failed to create type class instance for `Inhabited (Nat × ?m.1499)`" because the type has a missing part (i.e., the `_`).

```lean
#check_failure (inferInstance : Inhabited (Nat × _))
```

Instead  `#check` succeeds printing :
```
inferInstance : Inhabited (Nat × ?m.5)
```

And the same for this example from line 368

```lean
-- Error "failed to create type class instance for HMul Int ?m.1767 (?m.1797 x)"
#check_failure fun y => xs.map (fun x => hMul x y)
```

#check says:
```lean
fun y => List.map (fun x => hMulx x y) xs : (y : ?m.79) → List (?m.109 y)
```

### Steps to Reproduce

See above

**Expected behavior:** [What you expect to happen]

failure

**Actual behavior:** [What actually happens]

no failure, see CI failure:

https://github.com/leanprover/theorem_proving_in_lean4/runs/4193469732?check_suite_focus=true

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment] 2021-11-13 08:27
Whoops...

**Comment by leodemoura** [comment] 2021-11-18 16:29
@Kha This was an intended side-effect of a recent change. A few users asked for the `#check` to succeed even when there are pending TC problems. They pointed out that this is the behavior in Lean 3. 
The `#check_failure` is based on `#check`, and the change triggered this regression. 
The issues have been fixed, and I am closing the issue here.

**Closed by leodemoura** 2021-11-18 16:29 UTC
